version: "3.8"
services:
  db:
    image: postgres:16.0
    container_name: db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
    user: "123:126"
    volumes:
      - /var/lib/postgresql/16/main:/var/lib/postgresql/data
    ports:
      - "5450:5432"

  backend:
    build: ./backend
    container_name: backend_container
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/case-study
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: "0000"
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - db
      - backend