const tasks = [
  {
    taskTitle: "Task 1",
    description:
      "Complete the project documentation. Complete the project documentation. Complete the project documentation. Complete the project documentation. Complete the project documentation. Complete the project documentation. Complete the project documentation.",
    startDate: new Date("2024-09-20"),
    endDate: new Date("2024-09-25"),
    appraisal: "Appraisal 1",
    appraisable: true,
    selfRating: 8,
    adminRating: 9,
  },
  {
    taskTitle: "Task 2",
    description: "Develop the user authentication module.",
    startDate: new Date("2024-09-21"),
    endDate: new Date("2024-09-26"),
    appraisal: "Appraisal 2",
    appraisable: true,
    selfRating: 7,
    adminRating: 8,
  },
  {
    taskTitle: "Task 3",
    description: "Test the API endpoints for errors.",
    startDate: new Date("2024-09-22"),
    endDate: new Date("2024-09-27"),
    appraisal: "null",
    appraisable: false,
    selfRating: 0,
    adminRating: 0,
  },
  {
    taskTitle: "Task 4",
    description: "Fix the reported UI bugs in the dashboard.",
    startDate: new Date("2024-09-23"),
    endDate: new Date("2024-09-28"),
    appraisal: "Appraisal 1",
    appraisable: true,
    selfRating: 6,
    adminRating: 7,
  },
  {
    taskTitle: "Task 5",
    description: "Optimize database queries for better performance.",
    startDate: new Date("2024-09-24"),
    endDate: new Date("2024-09-29"),
    appraisal: "Appraisal 2",
    appraisable: true,
    selfRating: 9,
    adminRating: 9,
  },
  {
    taskTitle: "Task 6",
    description: "Implement the new notification system.",
    startDate: new Date("2024-09-25"),
    endDate: new Date("2024-09-30"),
    appraisal: "Appraisal 3",
    appraisable: true,
    selfRating: 8,
    adminRating: 9,
  },
];

export default tasks;
